# Generated by Django 5.2.8 on 2025-11-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_rename_nombre_reserva_huesped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='huesped',
            new_name='nombre',
        ),
    ]
