# Generated by Django 5.2.8 on 2025-11-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_rename_huesped_reserva_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre',
            new_name='huesped',
        ),
    ]
