# Generated by Django 5.2.8 on 2025-11-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_rename_nombre_reserva_huesped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='direccion',
            new_name='habitacion',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='huesped',
            new_name='reserva',
        ),
    ]
