# Generated by Django 5.2.8 on 2025-11-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_rename_direccion_reserva_habitacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='reserva',
            new_name='huesped',
        ),
    ]
