# Generated by Django 5.2.8 on 2025-11-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huesped', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='direccion',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='huesped',
            old_name='telefono',
            new_name='descripcion',
        ),
    ]
