# Generated by Django 5.2.8 on 2025-11-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huesped', '0002_rename_direccion_huesped_capacidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='nombre',
            new_name='huesped',
        ),
    ]
