# Generated by Django 5.2.8 on 2025-11-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoabitacion', '0002_habitacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='habitacion',
        ),
    ]
