# Generated by Django 5.2.8 on 2025-11-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='direccion',
            new_name='piso',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='telefono',
            new_name='precio_noche',
        ),
    ]
