# Generated by Django 5.2.8 on 2025-11-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_rename_direccion_habitacion_piso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='precio_noche',
            new_name='precio',
        ),
    ]
