# Generated by Django 5.2.8 on 2025-11-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_rename_precio_noche_habitacion_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='precio',
            new_name='apellido',
        ),
    ]
